import Head from "next/head";
import Image from "next/image";
import { FormEvent, useState } from "react";
import styles from "../styles/Home.module.css";
import { getUserFavouriteLanguage } from "../utils/getUserLanguages";

export default function Home() {
  const [error, setError] = useState("");
  const [usernameInput, setUsernameInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [favLang, setFavLang] = useState("");

  async function onClickHandler(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    try {
      if (!usernameInput) {
        setError("Please enter username into input field");
        return;
      }
      setIsLoading(true);
      const data = await getUserFavouriteLanguage(usernameInput);
      console.log(data);
      setFavLang(data);
      setError("");
      setIsLoading(false);
    } catch (e) {
      console.log(e);
      setError("Unable to retrieve favourite language");
      setFavLang("");
    }
    setIsLoading(false);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={(e) => onClickHandler(e)}>
          <input
            placeholder="Enter Username Here..."
            type="text"
            value={usernameInput}
            onChange={(e) => setUsernameInput(e.target.value)}
          />
          <button>Load user languages</button>
        </form>
        {isLoading && <p>Loading...</p>}
        {error && <p>Error: {error}</p>}
        {favLang && <p>Favourite language is {favLang}</p>}
      </main>
    </div>
  );
}
